# This is based on ripgrep:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/ci.yml

name: ci
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
        - '**'
jobs:
  test:
    name: test
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS:
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Features to use. When cross is used, `vendored-openssl` is enabled
      FEATURES:
      # This is used to build in release mode on Windows
      ADDITIONAL:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable
        - beta
        - nightly
        - musl
        - gnu-32
        - musl-32
        - arm
        - armv7
        - aarch
        - macos
        - win-msvc
        - win-gnu
        - win32-msvc
        - win32-gnu
        include:
        - build: stable
          os: ubuntu-18.04
          rust: stable
        - build: beta
          os: ubuntu-18.04
          rust: beta
        - build: nightly
          os: ubuntu-18.04
          rust: nightly
        - build: musl
          os: ubuntu-18.04
          rust: stable
          target: x86_64-unknown-linux-musl
        - build: gnu-32
          os: ubuntu-18.04
          rust: stable
          target: i686-unknown-linux-gnu
        - build: musl-32
          os: ubuntu-18.04
          rust: stable
          target: i686-unknown-linux-musl
        - build: arm
          os: ubuntu-18.04
          rust: stable
          target: arm-unknown-linux-gnueabi
        - build: armv7
          os: ubuntu-18.04
          rust: stable
          target: armv7-unknown-linux-gnueabihf
        - build: aarch
          os: ubuntu-18.04
          rust: stable
          target: aarch64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          rust: stable
        - build: win-msvc
          os: windows-2019
          rust: stable
        - build: win-gnu
          os: windows-2019
          rust: stable-x86_64-gnu
        - build: win32-msvc
          os: windows-2019
          rust: stable
          target: i686-pc-windows-msvc
        - build: win32-gnu
          os: windows-2019
          rust: stable-i686-pc-windows-gnu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Use cache
      uses: Swatinem/rust-cache@v1

    - name: Use Cross
      if: matrix.target != ''
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV
        echo "FEATURES=--features vendored-openssl" >> $GITHUB_ENV

    # Building sqlx in debug mode fails on Windows.
    # More info: https://github.com/launchbadge/sqlx/issues/615
    - name: Release Build
      if: runner.os == 'Windows'
      run: echo "ADDITIONAL=--release" >> $GITHUB_ENV
      shell: bash

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "features are: ${{ env.FEATURES }}"
        echo "additional: ${{ env.ADDITIONAL }}"

    - name: Build tvm_assistant
      run: ${{ env.CARGO }} build ${{ env.ADDITIONAL }} ${{ env.TARGET_FLAGS }} ${{ env.FEATURES }}

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
